In [4]:
import pandas as pd

file_path = "../data/raw_financials.xlsx"

excel_file = pd.ExcelFile(file_path)
excel_file.sheet_names

['Company_Master',
 'Raw_Financials',
 'Panel_Data',
 'Risk_Scoring_Panel',
 'Dashboard']

In [5]:
import pandas as pd

file_path = "../data/raw_financials.xlsx"

df = pd.read_excel(
    file_path,
    sheet_name="Raw_Financials",
    dtype={"stock_code": str}
)

df.columns = df.columns.str.strip()

df["stock_code"] = df["stock_code"].str.zfill(6)

df.head()

,row_id,stock_code,company,year,industry_group,chain_position,revenue,operating_cost,net_profit_attr,exact_overseas_revenue,proxy_export_sales,inventory_begin,inventory_end,ar_begin,ar_end,operating_cash_flow,rnd_expense,capex_cash_paid,foreign_revenue_type,source_check_status
0,000977_2021,000977,浪潮信息,2021,server_infra,AI_server,6.704755e+06,5.937932e+06,200273.839178,7.081686e+05,NaN,1.094326e+06,2.240223e+06,8.207352e+05,1.196977e+06,-828957.397199,292129.481357,19486.419515,exact_overseas_revenue,checked
1,000977_2022,000977,浪潮信息,2022,server_infra,AI_server,6.963532e+06,6.175312e+06,208035.092643,9.164556e+05,NaN,2.240223e+06,1.502463e+06,1.196977e+06,1.104141e+06,181335.049074,319741.542434,113365.608279,exact_overseas_revenue,checked
2,000977_2023,000977,浪潮信息,2023,server_infra,AI_server,6.586659e+06,5.925272e+06,178278.432291,9.547103e+05,NaN,1.502492e+06,1.911457e+06,1.109973e+06,9.110557e+05,52038.338846,307102.048324,30697.649790,exact_overseas_revenue,checked
3,000977_2024,000977,浪潮信息,2024,server_infra,AI_server,1.150285e+07,1.070897e+07,229356.317858,3.408139e+06,NaN,1.911457e+06,4.063318e+06,9.880616e+03,1.162336e+06,7486.635936,354983.628039,24787.448268,exact_overseas_revenue,checked
4,000977_2025,000977,浪潮信息,2025,server_infra,AI_server,1.647820e+07,1.567350e+07,241286.630876,NaN,NaN,4.067893e+06,4.650785e+06,1.164276e+06,1.305056e+06,545305.205422,381198.598516,22509.546643,not_disclosed,checked

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 20 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   row_id                  50 non-null     str
 1   stock_code              50 non-null     str
 2   company                 50 non-null     str
 3   year                    50 non-null     int64
 4   industry_group          50 non-null     str
 5   chain_position          50 non-null     str
 6   revenue                 50 non-null     float64
 7   operating_cost          50 non-null     float64
 8   net_profit_attr         50 non-null     float64
 9   exact_overseas_revenue  31 non-null     float64
 10  proxy_export_sales      11 non-null     float64
 11  inventory_begin         50 non-null     float64
 12  inventory_end           50 non-null     float64
 13  ar_begin                50 non-null     float64
 14  ar_end                  50 non-null     float64
 15  operating_cash_flow     50 non-null     float64
 16  rnd_expense             50 non-null     float64
 17  capex_cash_paid         50 non-null     float64
 18  foreign_revenue_type    50 non-null     str
 19  source_check_status     50 non-null     str
dtypes: float64(12), int64(1), str(7)
memory usage: 7.9 KB

In [7]:
list(df.columns)

['row_id',
 'stock_code',
 'company',
 'year',
 'industry_group',
 'chain_position',
 'revenue',
 'operating_cost',
 'net_profit_attr',
 'exact_overseas_revenue',
 'proxy_export_sales',
 'inventory_begin',
 'inventory_end',
 'ar_begin',
 'ar_end',
 'operating_cash_flow',
 'rnd_expense',
 'capex_cash_paid',
 'foreign_revenue_type',
 'source_check_status']

In [8]:
df.isna().sum()

row_id                     0
stock_code                 0
company                    0
year                       0
industry_group             0
chain_position             0
revenue                    0
operating_cost             0
net_profit_attr            0
exact_overseas_revenue    19
proxy_export_sales        39
inventory_begin            0
inventory_end              0
ar_begin                   0
ar_end                     0
operating_cash_flow        0
rnd_expense                0
capex_cash_paid            0
foreign_revenue_type       0
source_check_status        0
dtype: int64

In [9]:
df.dtypes

row_id                        str
stock_code                    str
company                       str
year                        int64
industry_group                str
chain_position                str
revenue                   float64
operating_cost            float64
net_profit_attr           float64
exact_overseas_revenue    float64
proxy_export_sales        float64
inventory_begin           float64
inventory_end             float64
ar_begin                  float64
ar_end                    float64
operating_cash_flow       float64
rnd_expense               float64
capex_cash_paid           float64
foreign_revenue_type          str
source_check_status           str
dtype: object

In [10]:
df.shape

(50, 20)

In [11]:
df["company"].value_counts()

company
浪潮信息    5
工业富联    5
中科曙光    5
紫光股份    5
神州数码    5
沪电股份    5
深南电路    5
胜宏科技    5
中际旭创    5
新易盛     5
Name: count, dtype: int64

In [12]:
df.duplicated(subset=["stock_code", "year"]).sum()

np.int64(0)

In [13]:
df["year"].value_counts().sort_index()

year
2021    10
2022    10
2023    10
2024    10
2025    10
Name: count, dtype: int64

In [14]:
df["foreign_revenue_type"].value_counts()

foreign_revenue_type
exact_overseas_revenue    31
proxy_export_sales        11
not_disclosed              8
Name: count, dtype: int64

In [15]:
conflict_rows = df[
    df["exact_overseas_revenue"].notna() &
    df["proxy_export_sales"].notna()
]

conflict_rows

Empty DataFrame
Columns: [row_id, stock_code, company, year, industry_group, chain_position, revenue, operating_cost, net_profit_attr, exact_overseas_revenue, proxy_export_sales, inventory_begin, inventory_end, ar_begin, ar_end, operating_cash_flow, rnd_expense, capex_cash_paid, foreign_revenue_type, source_check_status]
Index: []

In [16]:
import numpy as np

df_feature = df.copy()

# 按公司和年份排序，方便计算同比增长
df_feature = df_feature.sort_values(["stock_code", "year"]).reset_index(drop=True)

# 1. 统一境外收入口径：优先 exact，其次 proxy
df_feature["foreign_revenue_used"] = df_feature["exact_overseas_revenue"].fillna(
    df_feature["proxy_export_sales"]
)

# 2. 是否披露境外收入
df_feature["has_foreign_revenue_disclosure"] = df_feature["foreign_revenue_used"].notna().astype(int)

# 3. 境外收入占比
df_feature["foreign_revenue_ratio"] = df_feature["foreign_revenue_used"] / df_feature["revenue"]

# 4. 毛利与毛利率
df_feature["gross_profit"] = df_feature["revenue"] - df_feature["operating_cost"]
df_feature["gross_margin"] = df_feature["gross_profit"] / df_feature["revenue"]

# 5. 成本率
df_feature["cost_ratio"] = df_feature["operating_cost"] / df_feature["revenue"]

# 6. 归母净利率
df_feature["net_margin_attr"] = df_feature["net_profit_attr"] / df_feature["revenue"]

# 7. 经营现金流收入比
df_feature["ocf_margin"] = df_feature["operating_cash_flow"] / df_feature["revenue"]

# 8. 经营现金流 / 归母净利润
df_feature["ocf_to_net_profit"] = df_feature["operating_cash_flow"] / df_feature["net_profit_attr"]

# 9. 研发强度
df_feature["rnd_intensity"] = df_feature["rnd_expense"] / df_feature["revenue"]

# 10. 资本开支强度
df_feature["capex_intensity"] = df_feature["capex_cash_paid"] / df_feature["revenue"]

# 11. 平均存货与存货周转率
df_feature["avg_inventory"] = (
    df_feature["inventory_begin"] + df_feature["inventory_end"]
) / 2

df_feature["inventory_turnover"] = df_feature["operating_cost"] / df_feature["avg_inventory"]

# 12. 存货占收入比例
df_feature["inventory_to_revenue"] = df_feature["inventory_end"] / df_feature["revenue"]

# 13. 平均应收账款与应收账款周转率
df_feature["avg_ar"] = (
    df_feature["ar_begin"] + df_feature["ar_end"]
) / 2

df_feature["ar_turnover"] = df_feature["revenue"] / df_feature["avg_ar"]

# 14. 应收账款占收入比例
df_feature["ar_to_revenue"] = df_feature["ar_end"] / df_feature["revenue"]

# 15. 同比增长类特征
df_feature["revenue_growth_yoy"] = df_feature.groupby("stock_code")["revenue"].pct_change()
df_feature["net_profit_growth_yoy"] = df_feature.groupby("stock_code")["net_profit_attr"].pct_change()
df_feature["ocf_growth_yoy"] = df_feature.groupby("stock_code")["operating_cash_flow"].pct_change()
df_feature["inventory_growth_yoy"] = df_feature.groupby("stock_code")["inventory_end"].pct_change()
df_feature["ar_growth_yoy"] = df_feature.groupby("stock_code")["ar_end"].pct_change()

# 16. 清理无穷值
df_feature = df_feature.replace([np.inf, -np.inf], np.nan)

df_feature.head()

,row_id,stock_code,company,year,industry_group,chain_position,revenue,operating_cost,net_profit_attr,exact_overseas_revenue,...,inventory_turnover,inventory_to_revenue,avg_ar,ar_turnover,ar_to_revenue,revenue_growth_yoy,net_profit_growth_yoy,ocf_growth_yoy,inventory_growth_yoy,ar_growth_yoy
0,000034_2021,000034,神州数码,2021,server_infra,IT_distribution_compute_integration,1.223849e+07,1.182818e+07,24916.304706,9.096845e+05,...,9.810202,0.118917,7.899975e+05,15.491805,0.068176,NaN,NaN,NaN,NaN,NaN
1,000034_2022,000034,神州数码,2022,server_infra,IT_distribution_compute_integration,1.158800e+07,1.113330e+07,100440.551288,1.039467e+06,...,8.232075,0.107827,8.537108e+05,13.573685,0.075341,-0.053151,3.031117,-6.357577,-0.141451,0.046354
2,000034_2023,000034,神州数码,2023,server_infra,IT_distribution_compute_integration,1.196239e+07,1.148910e+07,117178.300653,1.296473e+06,...,9.253223,0.103137,1.001138e+06,11.948790,0.094398,0.032308,0.166643,-1.180993,-0.012592,0.293429
3,000034_2024,000034,神州数码,2024,server_infra,IT_distribution_compute_integration,1.281664e+07,1.227696e+07,75269.464923,1.558867e+06,...,9.839724,0.098436,1.167933e+06,10.973784,0.094146,0.071411,-0.357650,-17.543356,0.022577,0.068552
4,000034_2025,000034,神州数码,2025,server_infra,IT_distribution_compute_integration,1.437510e+07,1.388670e+07,52294.384322,2.237701e+06,...,8.790379,0.132027,1.276768e+06,11.258977,0.093697,0.121597,-0.305238,-1.968511,0.504336,0.116241

In [17]:
df_feature.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 42 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   row_id                          50 non-null     str
 1   stock_code                      50 non-null     str
 2   company                         50 non-null     str
 3   year                            50 non-null     int64
 4   industry_group                  50 non-null     str
 5   chain_position                  50 non-null     str
 6   revenue                         50 non-null     float64
 7   operating_cost                  50 non-null     float64
 8   net_profit_attr                 50 non-null     float64
 9   exact_overseas_revenue          31 non-null     float64
 10  proxy_export_sales              11 non-null     float64
 11  inventory_begin                 50 non-null     float64
 12  inventory_end                   50 non-null     float64
 13  ar_begin                        50 non-null     float64
 14  ar_end                          50 non-null     float64
 15  operating_cash_flow             50 non-null     float64
 16  rnd_expense                     50 non-null     float64
 17  capex_cash_paid                 50 non-null     float64
 18  foreign_revenue_type            50 non-null     str
 19  source_check_status             50 non-null     str
 20  foreign_revenue_used            42 non-null     float64
 21  has_foreign_revenue_disclosure  50 non-null     int64
 22  foreign_revenue_ratio           42 non-null     float64
 23  gross_profit                    50 non-null     float64
 24  gross_margin                    50 non-null     float64
 25  cost_ratio                      50 non-null     float64
 26  net_margin_attr                 50 non-null     float64
 27  ocf_margin                      50 non-null     float64
 28  ocf_to_net_profit               50 non-null     float64
 29  rnd_intensity                   50 non-null     float64
 30  capex_intensity                 50 non-null     float64
 31  avg_inventory                   50 non-null     float64
 32  inventory_turnover              50 non-null     float64
 33  inventory_to_revenue            50 non-null     float64
 34  avg_ar                          50 non-null     float64
 35  ar_turnover                     50 non-null     float64
 36  ar_to_revenue                   50 non-null     float64
 37  revenue_growth_yoy              40 non-null     float64
 38  net_profit_growth_yoy           40 non-null     float64
 39  ocf_growth_yoy                  40 non-null     float64
 40  inventory_growth_yoy            40 non-null     float64
 41  ar_growth_yoy                   40 non-null     float64
dtypes: float64(33), int64(2), str(7)
memory usage: 16.5 KB

In [18]:
df_feature.isna().sum()

row_id                             0
stock_code                         0
company                            0
year                               0
industry_group                     0
chain_position                     0
revenue                            0
operating_cost                     0
net_profit_attr                    0
exact_overseas_revenue            19
proxy_export_sales                39
inventory_begin                    0
inventory_end                      0
ar_begin                           0
ar_end                             0
operating_cash_flow                0
rnd_expense                        0
capex_cash_paid                    0
foreign_revenue_type               0
source_check_status                0
foreign_revenue_used               8
has_foreign_revenue_disclosure     0
foreign_revenue_ratio              8
gross_profit                       0
gross_margin                       0
cost_ratio                         0
net_margin_attr                    0
ocf_margin                         0
ocf_to_net_profit                  0
rnd_intensity                      0
capex_intensity                    0
avg_inventory                      0
inventory_turnover                 0
inventory_to_revenue               0
avg_ar                             0
ar_turnover                        0
ar_to_revenue                      0
revenue_growth_yoy                10
net_profit_growth_yoy             10
ocf_growth_yoy                    10
inventory_growth_yoy              10
ar_growth_yoy                     10
dtype: int64

In [19]:
missing_summary = df_feature.isna().sum()
missing_summary[missing_summary > 0]

exact_overseas_revenue    19
proxy_export_sales        39
foreign_revenue_used       8
foreign_revenue_ratio      8
revenue_growth_yoy        10
net_profit_growth_yoy     10
ocf_growth_yoy            10
inventory_growth_yoy      10
ar_growth_yoy             10
dtype: int64

In [20]:
conflict_rows = df_feature[
    df_feature["exact_overseas_revenue"].notna() &
    df_feature["proxy_export_sales"].notna()
]

conflict_rows[[
    "row_id",
    "company",
    "year",
    "exact_overseas_revenue",
    "proxy_export_sales",
    "foreign_revenue_type"
]]

Empty DataFrame
Columns: [row_id, company, year, exact_overseas_revenue, proxy_export_sales, foreign_revenue_type]
Index: []

In [21]:
feature_cols = [
    "row_id",
    "stock_code",
    "company",
    "year",
    "revenue",
    "foreign_revenue_used",
    "foreign_revenue_ratio",
    "gross_margin",
    "net_margin_attr",
    "ocf_margin",
    "rnd_intensity",
    "capex_intensity",
    "inventory_turnover",
    "ar_turnover",
    "revenue_growth_yoy",
    "net_profit_growth_yoy"
]

df_feature[feature_cols].head(15)

,row_id,stock_code,company,year,revenue,foreign_revenue_used,foreign_revenue_ratio,gross_margin,net_margin_attr,ocf_margin,rnd_intensity,capex_intensity,inventory_turnover,ar_turnover,revenue_growth_yoy,net_profit_growth_yoy
0,000034_2021,000034,神州数码,2021,1.223849e+07,9.096845e+05,0.074330,0.033526,0.002036,-0.001276,0.001964,0.002993,9.810202,15.491805,NaN,NaN
1,000034_2022,000034,神州数码,2022,1.158800e+07,1.039467e+06,0.089702,0.039239,0.008668,0.007218,0.002513,0.002092,8.232075,13.573685,-0.053151,3.031117
2,000034_2023,000034,神州数码,2023,1.196239e+07,1.296473e+06,0.108379,0.039565,0.009796,-0.001266,0.002874,0.003409,9.253223,11.948790,0.032308,0.166643
3,000034_2024,000034,神州数码,2024,1.281664e+07,1.558867e+06,0.121628,0.042108,0.005873,0.019542,0.002938,0.004589,9.839724,10.973784,0.071411,-0.357650
4,000034_2025,000034,神州数码,2025,1.437510e+07,2.237701e+06,0.155665,0.033976,0.003638,-0.016874,0.002731,0.003331,8.790379,11.258977,0.121597,-0.305238
5,000938_2021,000938,紫光股份,2021,6.763754e+06,2.231763e+05,0.032996,0.194682,0.031752,-0.032233,0.071101,0.007789,3.881180,6.680489,NaN,NaN
6,000938_2022,000938,紫光股份,2022,7.405765e+06,2.322918e+05,0.031366,0.206402,0.029138,0.054262,0.071550,0.006519,3.037449,6.147335,0.094919,0.004785
7,000938_2023,000938,紫光股份,2023,7.730781e+06,2.695936e+05,0.034873,0.195968,0.027203,-0.024024,0.073000,0.012167,2.578678,5.704355,0.043887,-0.025443
8,000938_2024,000938,紫光股份,2024,7.902408e+06,3.067025e+05,0.038811,0.173896,0.019898,0.030886,0.064560,0.006751,2.015465,5.659947,0.022200,-0.252296
9,000938_2025,000938,紫光股份,2025,9.674834e+06,4.710528e+05,0.048688,0.145909,0.017422,0.036039,0.051191,0.006337,2.055131,7.303255,0.224289,0.071919
10,000977_2021,000977,浪潮信息,2021,6.704755e+06,7.081686e+05,0.105622,0.114370,0.029870,-0.123637,0.043570,0.002906,3.561461,6.645898,NaN,NaN
11,000977_2022,000977,浪潮信息,2022,6.963532e+06,9.164556e+05,0.131608,0.113192,0.029875,0.026041,0.045917,0.016280,3.299936,6.052303,0.038596,0.038753
12,000977_2023,000977,浪潮信息,2023,6.586659e+06,9.547103e+05,0.144946,0.100413,0.027067,0.007901,0.046625,0.004661,3.471213,6.518125,-0.054121,-0.143037
13,000977_2024,000977,浪潮信息,2024,1.150285e+07,3.408139e+06,0.296286,0.069016,0.019939,0.000651,0.030860,0.002155,3.584726,19.625809,0.746386,0.286506
14,000977_2025,000977,浪潮信息,2025,1.647820e+07,NaN,NaN,0.048834,0.014643,0.033093,0.023134,0.001366,3.595385,13.346279,0.432532,0.052017

In [22]:
feature_check_cols = [
    "foreign_revenue_ratio",
    "gross_margin",
    "cost_ratio",
    "net_margin_attr",
    "ocf_margin",
    "ocf_to_net_profit",
    "rnd_intensity",
    "capex_intensity",
    "inventory_turnover",
    "inventory_to_revenue",
    "ar_turnover",
    "ar_to_revenue",
    "revenue_growth_yoy",
    "net_profit_growth_yoy",
    "ocf_growth_yoy",
    "inventory_growth_yoy",
    "ar_growth_yoy"
]

df_feature[feature_check_cols].describe()

,foreign_revenue_ratio,gross_margin,cost_ratio,net_margin_attr,ocf_margin,ocf_to_net_profit,rnd_intensity,capex_intensity,inventory_turnover,inventory_to_revenue,ar_turnover,ar_to_revenue,revenue_growth_yoy,net_profit_growth_yoy,ocf_growth_yoy,inventory_growth_yoy,ar_growth_yoy
count,42.000000,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000,40.000000,40.000000,40.000000,40.000000,40.000000
mean,0.443568,0.216698,0.783302,0.111753,0.111225,0.806426,0.049192,0.083616,4.079475,0.266016,6.470969,0.201680,0.294037,0.474804,1.475172,0.282961,0.233363
std,0.341405,0.119789,0.119789,0.092388,0.109474,1.359598,0.026384,0.081622,2.274774,0.122246,3.371181,0.078049,0.449376,0.876854,11.995742,0.598405,0.444332
min,0.000000,0.033526,0.521944,0.002036,-0.123637,-4.638547,0.001964,0.001366,1.400059,0.098436,2.724408,0.068176,-0.083955,-0.357650,-17.543356,-0.462332,-0.244373
25%,0.106311,0.103608,0.694916,0.029872,0.021397,0.477883,0.032260,0.008883,2.255359,0.168872,4.726051,0.159879,0.037024,0.004380,-0.799111,-0.014581,0.038296
50%,0.367470,0.235709,0.764291,0.104622,0.098032,1.011075,0.048909,0.070033,3.573093,0.230119,5.490192,0.191873,0.130885,0.172982,0.048929,0.134756,0.142062
75%,0.785657,0.305084,0.896392,0.158862,0.189547,1.564568,0.068563,0.143698,4.879657,0.333496,6.655081,0.238351,0.369801,0.567519,0.665946,0.490272,0.280217
max,0.961583,0.478056,0.966474,0.383704,0.402241,3.327466,0.111691,0.342977,9.839724,0.532188,19.625809,0.404198,1.872943,3.122565,71.837147,3.289277,2.549706

In [23]:
from pathlib import Path

current_dir = Path.cwd()

if current_dir.name == "notebooks":
    project_root = current_dir.parent
else:
    project_root = current_dir

output_dir = project_root / "outputs"
output_dir.mkdir(exist_ok=True)

if "stock_code" in df_feature.columns:
    df_feature["stock_code"] = df_feature["stock_code"].astype(str).str.zfill(6)

csv_path = output_dir / "df_feature_for_model.csv"
xlsx_path = output_dir / "df_feature_for_model.xlsx"

df_feature.to_csv(csv_path, index=False, encoding="utf-8-sig")
df_feature.to_excel(xlsx_path, index=False, sheet_name="features")

print("df_feature 保存完成")
print("当前工作目录：", current_dir)
print("项目根目录：", project_root)
print("CSV 文件：", csv_path)
print("Excel 文件：", xlsx_path)
print("df_feature 形状：", df_feature.shape)

df_feature 保存完成
当前工作目录： d:\ai_supply_chain_risk\notebooks
项目根目录： d:\ai_supply_chain_risk
CSV 文件： d:\ai_supply_chain_risk\outputs\df_feature_for_model.csv
Excel 文件： d:\ai_supply_chain_risk\outputs\df_feature_for_model.xlsx
df_feature 形状： (50, 42)